name: Release Linux/MacOS
on: 
  workflow_dispatch:
    branches: [ master ]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Tcl
      run: sudo apt install tcl-dev
    - name: Build and test
      run: |
        git clone https://github.com/dbohdan/tcl-duktape.git
        cd tcl-duktape
        ./configure && make test
        ls -l
  macos-build:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and test
      run: |
        brew install tcl-tk@8
        git clone https://github.com/dbohdan/tcl-duktape.git
        cd tcl-duktape
        ./configure && make test
        ls -l

  windows:      
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: git mingw-w64-x86_64-toolchain make
    - name: build-it
      run:
        git clone https://github.com/dbohdan/tcl-duktape.git
        cd tcl-duktape
        ls
