name: Release Linux/MacOS
on: 
  workflow_dispatch:
    branches: [ master ]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Tcl
      run: sudo apt install tcl-dev
    - name: Build and test
      run: |
        git clone https://github.com/dbohdan/tcl-duktape.git
        cd tcl-duktape
        ./configure && make test
        ls -l
  macos-build:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and test
      run: |
        brew install tcl-tk@8
        echo -E "puts $::tcl_patchLevel" | tclsh
        ls /usr/local
        ls /usr/local/bin        
        find /usr/local -name tclConfig.sh
        find /usr/local -name "tclsh"
        git clone https://github.com/dbohdan/tcl-duktape.git
        cd tcl-duktape
        ls /System/Library/Frameworks/Tcl.framework/Versions/8.5/
        export PATH=/usr/local/Cellar/tcl-tk@8/8.6.16/bin/:$PATH
        find /usr/local/Cellar/tcl-tk@8/8.6.16/ -name "tclConfig.sh"
        echo -E "puts $::tcl_patchLevel" | tclsh
        ./configure --with-tcl=/usr/local/Cellar/tcl-tk@8/8.6.16 && make test
        ls -l
        ls /System/Library/Frameworks/Tcl.framework/Versions/Current
        find /System/Library/Frameworks/Tcl.framework/Versions -name "tclConfig.sh"
